---
latest_release_filename: /home/inception/bosh-space/release/openpaas-paasta-pinpoint-cluster-release/dev_releases/openpaas-paasta-pinpoint-cluster-release/openpaas-paasta-pinpoint-cluster-release-1.0.yml
